Task_1_3_1
nosikmy/OOP pull request #12
Opened 2022-11-16 22:12 UTC by nosikmy

2022-11-29 12:03 UTC, shadrina requested changes
Сколько на твоей машине исполняется 10-гиговый тест?

2022-11-29 12:03 UTC, shadrina commented on Task_1_3_1/src/main/java/ru/nsu/aramazanova1/CreatorBigFile.java
> +            throw new RuntimeException(e);
Мне кажется, тут будет правильнее в сигнатуре метода указать `throws IOException`. Это уменьшит вложенность внутри тела, и на тестах разницы не будет, так как все тесты с тем же throws в сигнатуре

2022-11-29 12:03 UTC, shadrina commented on Task_1_3_1/src/main/java/ru/nsu/aramazanova1/CreatorBigFile.java
> +            throw new RuntimeException(e);
То есть этот catch и оборачивание в RuntimeException здесь излишни.

2022-11-29 12:03 UTC, shadrina commented on Task_1_3_1/src/main/java/ru/nsu/aramazanova1/Substring.java
> +     * @return List of pairs of line and entry index
Если это пары, давай сделаем класс `Pair`. Будет гораздо красивее, чем список массивов.

2022-12-02 16:50 UTC, nosikmy commented on Task_1_3_1/src/main/java/ru/nsu/aramazanova1/Substring.java
> +     * @return List of pairs of line and entry index
![image](https://user-images.githubusercontent.com/91544344/205343737-48353c94-6904-4f76-b1e8-2b5cf40c11a6.png)

2022-12-07 04:00 UTC, shadrina requested changes

2022-12-07 04:00 UTC, shadrina commented on Task_1_3_1/src/main/java/ru/nsu/aramazanova1/Substring.java
> +        file.close();
Пусть его закрывает тот, кто делает инициализацию. Именно так кстати у тебя и происходит, потому что оно обернуто в try with resources

2022-12-07 04:00 UTC, shadrina commented on Task_1_3_1/src/test/java/ru/nsu/aramazanova1/SubstringTest.java
> +                new FileInputStream("src/test/resources/example1.txt"), UTF_8))) {
Надо правильно читать из ресурсов через getResourceAsStream

2022-12-20 10:58 UTC, shadrina requested changes
В PR почему-то файлы от предыдущих задач

2022-12-20 10:58 UTC, shadrina commented on Task_1_3_1/src/test/java/ru/nsu/aramazanova1/SubstringTest.java
> +        try (BufferedReader file = new BufferedReader(new InputStreamReader(
Слева Reader. Тут и далее.

2022-12-20 10:58 UTC, shadrina commented on Task_1_3_1/src/test/java/ru/nsu/aramazanova1/SubstringTest.java
> +        }
Зачем, если можно их сравнить по `equals`?

2022-12-20 10:58 UTC, shadrina commented on Task_1_3_1/src/test/java/ru/nsu/aramazanova1/SubstringTest.java
> +    public void bigFileTest() throws IOException, NullPointerException {
Почему тест может кинуть NPE? Вопрос на сдачу: чем отличаются проверяемые исключения от непроверяемых?

2022-12-27 18:14 UTC, nosikmy commented on Task_1_3_1/src/test/java/ru/nsu/aramazanova1/SubstringTest.java
> +    public void bigFileTest() throws IOException, NullPointerException {
Наличие обработки проверяемых проверяется компилятором, непроверяемые исключения мы можем не обрабатывать. Тест может кинуть NPE, если в InputStreamReader или delete подать null. Другие тесты тоже могут кинуть NPE

2023-02-13 06:40 UTC, merged