Task_1_4_1
nosikmy/OOP pull request #13
Opened 2022-11-23 15:51 UTC by nosikmy

2022-11-29 13:53 UTC, shadrina requested changes
1. Изменяется код предыдущей лабы
2. Не исправлены варнинги от ревьюдога

2022-12-08 11:37 UTC, shadrina requested changes
А почему название ветки, пул реквеста и директории отличаются? Какую задачу все-таки хочется сдать?

2022-12-08 16:56 UTC, nosikmy commented
Здравствуйте, Task_1_4_1, тут вроде бы все совпадает

2022-12-09 10:04 UTC, shadrina commented
Посмотри вкладку files changed, там изменения задачи 1_3_1 (вся папка). Ее надо убрать из этого PR.
Судя по всему, ветку этой задачи ты создала из ветки предыдущей, а надо было из мастера.

2022-12-09 14:53 UTC, closed without merging