Task_1_5_1
nosikmy/OOP pull request #14
Opened 2022-12-08 09:35 UTC by nosikmy

2022-12-13 07:03 UTC, Allody22 commented
Амин, у тебя в files changed много каких-то лишних файлов из других лаб, надо это пофиксить

2022-12-14 07:13 UTC, shadrina requested changes

2022-12-14 07:13 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/aramazanova1/Calculator.java
> +    public static Double forUnaryOperator(Double a, String operator) {
jetbrains annotation
на будущее

2022-12-14 07:13 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/aramazanova1/Calculator.java
> +            default -> null;
Кидать исключение

2022-12-27 16:57 UTC, shadrina approved these changes
Аккуратненько вышло, мне нравится

2022-12-27 19:21 UTC, merged